#!/usr/bin/env python3
"""
gen_init.py - turn a CaptureInit run into src/LB_TFTInit.h.

    python3 tools/gen_init.py /tmp/initcapture.txt

Why captured rather than transcribed: porting a panel driver usually dies on a
single mistyped byte, and the symptom is a black screen with no error at all.
These tables are several hundred bytes; transcribing them by hand would go
wrong, not might. Internal/LonelyBinaryDisplay/代码/CaptureInit plugs a
recording Arduino_DataBus into each Arduino_GFX driver and records exactly what
it sends - so the output is what currently ships, not a reading of a datasheet.

Output format, one entry per command:

    cmd, nbytes, delay_ms, data...

terminated by 0xFF, 0xFF. Delays live in the entry that precedes them, so the
stream stays a flat byte array with no separate table to keep in step.
"""
import sys, os, re

if len(sys.argv) < 2:
    sys.exit(__doc__.strip())

text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
blocks = re.split(r"^### ", text, flags=re.M)[1:]

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "LB_TFTInit.h")

made = []
with open(OUT, "w") as f:
    f.write("""#pragma once
/*
 * LB_TFTInit.h - GENERATED by tools/gen_init.py. Do not edit by hand.
 *
 * Panel initialisation sequences, CAPTURED from the Arduino_GFX drivers rather
 * than transcribed from datasheets: see tools/gen_init.py for why, and
 * Internal/LonelyBinaryDisplay/代码/CaptureInit for how. What is here is
 * exactly what the shipping library sends.
 *
 * Format: cmd, nbytes, delay_ms, data...   terminated by 0xFF, 0xFF.
 *
 * !! The delays are not decoration !!
 *   They were the easiest thing to lose in this port - a delay is a delay()
 *   call or a DELAY opcode, not a bus write, so the first version of the
 *   recorder missed every one of them. A panel that never gets its 120 ms
 *   after SLPOUT can come up black with nothing in the log.
 */
#include <stdint.h>
""")
    for b in blocks:
        head, _, body = b.partition("\n")
        name = head.split()[0]
        toks = re.findall(r"([CDTPR?])([0-9A-F]{2})", body)
        entries, cur = [], None
        for kind, hexv in toks:
            v = int(hexv, 16)
            if kind == "C":
                if cur: entries.append(cur)
                cur = [v, [], 0]
            elif kind == "D" and cur:
                cur[1].append(v)
            elif kind == "T" and cur:
                cur[2] = v
        if cur: entries.append(cur)

        data = []
        for cmd, payload, dly in entries:
            data += [cmd, len(payload), dly] + payload
        data += [0xFF, 0xFF]

        f.write(f"\n/* {name}: {len(entries)} commands, {len(data)} bytes */\n")
        f.write(f"static const uint8_t LB_INIT_{name}[{len(data)}] = {{\n")
        for i in range(0, len(data), 12):
            f.write("  " + ",".join(f"0x{x:02X}" for x in data[i:i+12]) + ",\n")
        f.write("};\n")
        made.append((name, len(entries), len(data), sum(1 for e in entries if e[2])))

for n, c, b, d in made:
    print(f"  {n:14s} {c:3d} 条命令  {b:4d} 字节  {d} 处延时")
print(f"wrote {os.path.normpath(OUT)}")
